print("Hi welcome to test wizard 1 please press enter to move on")
input()
print("please anwser honestly press enter to move on")
input()
print("what is 1+1")
input()
print("if you said 2 you are correct press enter to move on")
input()
print("2nd question what is biggest planet in the solar system")
input()
print("if you said Jupiter you are correct press enter to continue")
input()
print("3rd question what is 25/2")
input()
print("If you said 12.5 you are correct press enter to move on.")
input()
print("4th question what is type of object is Earth")
input()
print("If you said a planet you are correct press enter to move on ")
input()
print("5th question what is 5*100")
input()
print("if you said 5000 you are correct press enter to move on")
input()
print("6th quetsion fill in the blanks T_y")
input()
print("If you said Toy you are correct press enter to move on")
input()
print("7th question fill in the blank Ro__T")
input()
print("If you said Robot you are correct press enter to move on")
input()
print("8th question Fill in the blank pr_gr_m")
input()
print("If you said program you are correct press enter to move on")
input()
print("Last question put in order greatest to least 989 840 1009")
input()
print("if you said 1009 989 840 you are correct press enter to move on")
input()
print("put least to greatest 70010 959 9599")
input()
print("If you said 959 9599 70010 you are correct press enter to move on")
input()
print("Hope you enjoyed thanks for playing! press enter to finish the quiz")
input()
