print("Hi welcome to test wizard 1 please press enter to continue by press any button")
input()
print("please anwser honestly press enter to move on")
input()
print("what is 1+1")
input()
print("if you said 2 you are correct press enter to move on")
input()
print("2nd question what is biggest planet in the solar system")
input()
print("if you said Jupiter you are correct press enter to continue")
input()
print("3rd question what is 25/2")
input()
print("If you said 12.5 you are correct press any enter to move on.")
input()
print("4th question what is type of object is Earth")
input()
print("If you said a planet you are correct press enter to move on ")
input()
print("Final question what is 50*100")
input()
print("if you said 5000 you are correct press enter to move on")
input()
print("Hope you enjoyed thanks for playing! press enter to finish the quiz")
input()

