print("Hi welcome to test wizard 1 please press any button to continue by press any button")
input()
print("please anwser honestly press any button to move on")
input()
print("what is 1+1")
input()
print("if you said 2 you are correct press any button to move on")
input()
print("2nd question what is biggeest planet in the solar system")
input()
print("if you said Jupiter you are correct press any button to continue")
input()
print("final question what is 25/2")
input()
print("If you said 12.5 you are correct press any button to move on.")
input()
print("Hope you enjoyed thanks for playing!")
